steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:experimental']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '.',
        '-f',
        'packages/backend/Dockerfile',
        '-t',
        'europe-west2-docker.pkg.dev/coffee-with-platforms/backstage/backstage:dev',
      ]
    env:
      - 'DOCKER_BUILDKIT=1'
 
    # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west2-docker.pkg.dev/coffee-with-platforms/backstage/backstage:dev',
      ]