project                      = "coffee-with-platforms"
region                       = "europe-west2"
zone                         = "europe-west2-c"
artifact_registry_url        = "europe-west2-docker.pkg.dev"
artifact_registry_repository = "backstage"